name: Integración Continua Gradle

on:
  push:
    branches:
      - master

jobs:
  Start_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: wrapper

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run all tests
        run: ./gradlew test --info --rerun-tasks
