name: Integración Continua Gradle

on:
  push:
    branches:
      - master

jobs:
  Start_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: |
          docker build -t my-image-name .

      - name: Run tests in Docker container
        run: |
          docker run --rm my-image-name ./gradlew test

      - name: Generate test reports
        run: |
          mkdir -p reports
          cp -r build/reports/tests reports/
